version: '3.1'

services:
  kasmweb-desktop:
    image: kasmweb/desktop:1.14.0
    shm_size: 512m
    environment:
      - VNC_PW=password
    ports:
      - "6901:6901"
    stdin_open: true
    tty: true
    volumes:
      - ./kasm-user:/home/kasm-user
