version: '3.7'

services:
  web:
    image: eventyay/open-event-frontend
    container_name: opev-frontend
    restart: always
    env_file:
      - ${UMBREL_ROOT}/data/storage/open-event-frontend/.env
    environment:
      INJECT_ENV: 'true'
      FASTBOOT_DISABLED: 'true'
    volumes:
      - ${APP_DATA_DIR}/config:/app/config
    ports:
      - 4200:4000
