version: '3'

services:
  db:
    image: database
    container_name: ecommerce_database
    environment:
        MYSQL_ROOT_PASSWORD: change-me-passwd
    build:
        context: ${APP_DATA_DIR}/database/
        dockerfile: Dockerfile
    ports:
        - "9306:3306"
  web:
    depends_on:
        - db
    image: app
    container_name: ecommerce_web
    build:
        context: ${APP_DATA_DIR}
        dockerfile: Dockerfile
    ports:
        - "3001:80"
