ARG NODE_VERSION=14-stretch

FROM node:${NODE_VERSION} AS base

EXPOSE 1337

FROM base AS strapi


ARG STRAPI_VERSION
RUN yarn global add @strapi/strapi@${STRAPI_VERSION}
RUN yarn global add pm2

RUN mkdir /srv/app && chown 1000:1000 -R /srv/app

WORKDIR /srv/app

VOLUME /srv/app

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod 777 /usr/local/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["strapi", "develop"]
