version: '3.1'

services:
  app_proxy:
    environment:
      APP_HOST: kasmweb-desktop_1
      APP_PORT: 6901

  kasmweb-desktop:
    image: kasmweb/desktop:1.14.0
    shm_size: 512m
    environment:
      - VNC_PW=password
    ports:
      - "6901"
    stdin_open: true
    tty: true
    volumes:
      - ${UMBREL_ROOT}/kasm-default-profile:/home/kasm-default-profile