version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: wikijs_server_1
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"
  
  server:
    image: linuxserver/wikijs:2.5.300@sha256:e265e60b799302d7c953e52208e8e41488beabc03b0d1cc9cd8bdef96763d4cf
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/config:/config
